Makefile, cmd/local/local.go, cmd/root.go, cmd/version/version.go, cmd/version/version_test.go, create-release-builds, go.mod, internal/local/cmd.go, internal/local/cmd_test.go, internal/telemetry/segment.go, main.go
- rename module `airbyte.io` -> `github.com/airbytehq`
- fix `go install` issues
=> fix: rename module; airbyte.io -> github.com/airbytehq

README.md, cmd/local/local.go, cmd/root.go
- fix telemetry errors being output with the wrong format - %w -> %s
- remove extra whitespace
=> fix: error format and extra whitespace

internal/build/info.go, internal/build/info_test.go
If installed via `go install` the `build.Version` will not be set correctly and will default to `dev`.  The change will now attempt to set the `build.Version` to the `BuildInfo.Main.Version` in that situation.
=> feat: add BuildInfo support

Makefile, cmd/version/version.go, cmd/version/version_test.go, internal/build/info.go, internal/build/info_test.go
- ignore the `debug.ReadBuildInfo` value of `(devel)`
- add the following additional version information to the `version` command
- revision - the git has that was built
- time (of last modification) - the time associated with that git hash (or the last modification)
- modified - true if this build contains modified files not part of version control
- add make `test` target
=> feat: improve version output

internal/telemetry/segment.go
Publish the `build` version as both `build` and `script_version` to align with what [run-ab-platform](https://github.com/airbytehq/airbyte/blob/bc7b4cb44c8727929eb4fedd36cb9fb9dea38a27/run-ab-platform.sh#L161C6-L161C20) does.
=> fix: capture version as both `build` and `script_version`

go.mod, go.sum, internal/local/cmd.go
- replace custom browser launching code with [cli/browser](https://github.com/cli/browser/)
- change a browser-launch-failure from a failed install to a debug message and a successful install
=> fix: improve linux web-browser code

internal/cmd/local/check.go, internal/cmd/local/local_install.go, internal/local/cmd.go, internal/local/docker/docker.go
- on osx, don't fail the docker check if the second attempt is successful
- On osx, docker can be communicated with via `/var/run/docker.sock` or `~/.docker/run/docker.sock`.  The existing code was incorrectly failing this check if the second attempt (`~/.docker/run/docker.sock`) was successful.
- fix typo in error messages - `coud` -> `could`
- add `context` to `docker.New` call
- call `Ping` on the docker client before marking the client creation as successful
- Fix an issue where the client would be created but would fail when communicating with it at a later step.  This early `Ping` check establishes that we can communicate with the docker daemon before we consider our client successfully created.
=> fix: docker check on osx incorrectly failing

internal/cmd/local/k8s/client.go, internal/cmd/local/local/cmd.go
- trim whitespace from log messages
- this removes the double-newline at the end of the warning message
- fetch the current pod logs, not the previous
=> fix: warning log formatting

.github/workflows/pr.yml, internal/telemetry/client.go, internal/telemetry/client_test.go, internal/telemetry/config.go, internal/telemetry/config_test.go, internal/telemetry/segment.go, internal/telemetry/segment_test.go
- fix airbytehq/airbyte-internal-issues#7977
- convert the telemetry user_id type from ulid to uuid
- this is backwards compatible as this uses a new `*_uuid` field in the `analytics.yml` file
- update pr title check to be in sync with platform pr title check
- add a lot of tests to verify user_id transition happens correctly
=> feat: convert telemetry user_id from ulid to uuid

abctl_install.sh
Currently works for macos & linux (tested on debian&ubuntu).
Linux install is very naive, no use of packagers, just downloading the binary and installing on /usr/local/bin. Same on macos if brew is not installed.
The script can be use as is or through:
```
curl -LsfS https://get.airbyte.com | bash -
```
This would make for a VERY simple quickstart alongside `abctl`
Features:
Todo:
- early test, we pbly don't need the window binary and just rely on Linux bins running in wsl2
Notes:
- not true. `sudo` uses the caller's environment
=> feat: create an install script for abctl

internal/cmd/local/check_test.go, internal/cmd/local/local/cmd.go, internal/cmd/local/local/cmd_test.go, internal/telemetry/client.go, internal/telemetry/config.go, internal/telemetry/config_test.go, internal/telemetry/noop.go, internal/telemetry/segment.go, internal/telemetry/wrapper_test.go
- set `ARIBYTE_INSTALLATION_ID` env-var via helm
- `global.env_vars.AIRBYTE_INSTALLATION_ID=[user]`
- add `User` method to `telemetry.Client`
- this represents the user-id (a `uuid`) for telemetry purposes
=> feat: set env-var `AIRBYTE_INSTALLATION_ID`

internal/telemetry/client.go, internal/telemetry/client_test.go, internal/telemetry/config.go, internal/telemetry/config_test.go, internal/telemetry/segment.go, internal/telemetry/segment_test.go
- Related to airbytehq/airbyte#38745
- After further discussions with @aaronsteers, decided to rename this new field to `analytics_id`
- Update yaml reading/writing to be futureproof
- Persist unknown fields between reading and writing the `analytics.yml` file
=> fix: rename anonymous_user_uuid to analytics_id

internal/cmd/local/local/cmd.go, internal/cmd/local/local/cmd_test.go, internal/cmd/local/local/testdata/values.yml, internal/cmd/local/local_install.go
Adds the ability to specify an (optional) values file to be used when running the helm install command.
```
abctl local install --values=path/to/values.yml
```
Verified that the underlying helm client we're using will merge the `values.yml` contents and the `value's options` values together:
```go
// GetValuesMap returns the merged mapped out values of a chart,
// using both ValuesYaml and ValuesOptions
func (spec *ChartSpec) GetValuesMap(p getter.Providers) (map[string]interface{}, error) {
valuesYaml := map[string]interface{}{}
err := yaml.Unmarshal([]byte(spec.ValuesYaml), &valuesYaml)
if err != nil {
return nil, errors.Wrap(err, "Failed to Parse ValuesYaml")
}
valuesOptions, err := spec.ValuesOptions.MergeValues(p)
if err != nil {
return nil, errors.Wrap(err, "Failed to Parse …
```
=> feat: add `--values` flag to `local install` command

internal/cmd/local/k8s/cluster.go, internal/cmd/local/local/cmd.go
- fix airbytehq/airbyte-internal-issues#8569
- create the persisted volume directories before k8s does
- this is necessary as the k8s created directories will be owned by the user that is running the docker daemon, not the user that is running `abctl`
- set the permissions on the persisted volume directories to `0777`
- this is necessary due to the postgres image using a custom postgres/postgres user with uid/gid of `70:70` which may not exist on the host machine and therefore the directory needs globally writable permissions
=> fix: set proper ownership and permissions of the persisted volume directories

internal/cmd/local/local/cmd.go, internal/cmd/local/local/cmd_test.go
- fix airbytehq/airbyte-internal-issues#8352
- set the default cpu limit to 3 cores
- set the default mem limit to 4 gigs
=> feat: increase default cpu/mem limits

internal/cmd/local/check_test.go, internal/cmd/local/docker/docker.go, internal/cmd/local/docker/docker_test.go
- fix airbytehq/airbyte-internal-issues#8594
- if the two images used for the `--migrate` command are not already on the host, pull them
- the images must exist before the `--migrate` command can successfully start
=> fix: pull docker images for migration if they don't already exist

internal/telemetry/config.go, internal/telemetry/config_test.go
- fix airbytehq/airbyte#40745
- verify the analytics configuration keys `analytics_id` and `anonymous_user_id` are strings
- Prior to this fix, if the keys `analytics_id` or `anonymous_user_id` existed in the `analytics.yml` file without a value (`analytics_id:`), the code would incorrectly assume that a valid key also meant a valid value and would panic if this turned out to not be the case.
- add two tests to also verify the panic existing behavior and fixed new behavior
=> fix: nil `analytics_id`/`anonymous_user_id` causing panics

internal/cmd/local/local/cmd.go
- fix typo - `serveral` -> `several`
=> chore: fix typo

internal/cmd/local/check.go
- fix an issue where the listener would fail to start and the error returned could be ignored
- this would happen if 
- the initial listen action failed (b/c the port was available)
- a request to what was listening on the port returned a http response
- the http response was anything other than a `401`
- replace `net.Listener` to use context aware `net.ListenConfig` instead
=> fix: panic related to port listener

internal/cmd/local/k8s/cluster.go, internal/cmd/local/k8s/provider.go
- add support for outputting kind log messages
- by default these message are noops, this PR creates a implementation that converts them to the pterm debug logger 
- increase wait-time for kind cluster; 2m -> 5m
=> feat: add debug logging for kind commands

internal/cmd/local/helm/helm.go, internal/cmd/local/local/cmd.go, internal/cmd/local/local/cmd_test.go
- replace the `noopWriter` with a `helmLogger`
- helm generates _a lot_ of logs, which is why it was originally noop'd but there may be some useful information in those logs, which is why they are not output as debug logs
=> feat: add debug logs for helm

internal/cmd/local/check.go, internal/cmd/local/helm/helm.go, internal/cmd/local/k8s/client.go, internal/cmd/local/local/cmd.go, internal/cmd/local/local/cmd_test.go, internal/cmd/local/local_install.go, internal/cmd/local/local_status.go, internal/cmd/local/local_uninstall.go
- add support for creating secrets via the `--secret` flag
```
abctl local install --secret=/path/to/secrets.yml
```
```yml
apiVersion: v1
kind: Secret
metadata:
name: secret-name
stringData:
key: value
```
- multiple `--secret` flags can be provided
```
abctl local install --secret=/path/to/secret-a.yml --secret=/path/to/secret-b.yml
```   
- update error messages for consistency
=> feat: add support for --secret

internal/cmd/local/local/cmd.go, internal/cmd/local/local/cmd_test.go
- fix https://github.com/airbytehq/airbyte-internal-issues/issues/8843
- workaround the problem with nginx upgrade failing by avoiding the upgrade entirely
- if the installed nginx chart `version` and `appversion` match the chart, skip the upgrade
=> feat: check nginx chart needs to be installed before installing

internal/cmd/local/local/cmd.go, internal/cmd/local/local/cmd_test.go, internal/maps/maps.go, internal/maps/maps_test.go
`abctl` defines certain helm values differently then their default values in Airbyte's helm charts. Specifically increasing the `global.jobs.resource.limits` values, as increasing these values improves sync performance significantly in comparison to docker-compose on resource rich machines.
The idea was that users could override any value defined in the helm charts _or_ in `abctl` by specifying a `--values` flag.  Unfortunately this was not the case, the values within `abctl` were overriding any values provided by the `--values` flag.
To fix this, this PR now treats these internal overrides as a separate `values.yml` file (that only exists in memory) and will now overlay the user defined `--values` on top of it, ensuring that the user defined `--values` always takes higher priority.
- fix …
=> fix: ensure `--values` settings override internal defaults

internal/cmd/local/k8s/provider.go, internal/cmd/local/local/cmd.go, internal/cmd/local/local_install.go
- fix https://github.com/airbytehq/airbyte-internal-issues/issues/8889
- add support for a `--no-browser` flag
- if provided, the browser will not attempt to launch
- this is for situations where a browser may not exist (e.g. installing on an EC2 instance)
=> feat: add --no-browser flag

go.mod, go.sum
- update docker to address [CVE-2024-41110](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-41110)
=> chore: update to docker 27.1.1

internal/cmd/local/local.go, internal/cmd/local/local/cmd.go, internal/cmd/local/local/cmd_test.go, internal/cmd/local/local_install.go
- deprecate `--username`
- deprecate `--password`
- add deprecation warning output if either `--username` or `--password` is defined
- include message that these have been replaced with a randomly generated password
- include message with how to fetch this randomly generated password (`abctl local credentials`) 
- remove deprecation warning for `--dnt`
- remove all references to `--dnt`
=> chore: deprecate --username and --password

internal/cmd/local/local_install.go
- hide the deprecated `username` and `password` flags
=> fix: hide deprecated flags from output

internal/cmd/local/local_install.go
- fix https://github.com/airbytehq/airbyte-internal-issues/issues/8890
- deprecate `--host` flag
- add `--external-host` flag
- if `--external-host` is specified, use it regardless of `--host`
- if `--host` is specified, output a deprecation warning and
- if `--external-host` is specified, use `--external-host`
- if `--external-host` is not specified, use `--host`
=> chore: deprecate `--host`, add `--external-host`

internal/cmd/local/check.go, internal/cmd/local/check_test.go, internal/cmd/local/local/cmd.go, internal/cmd/local/local/specs.go, internal/cmd/local/local_install.go
- fix https://github.com/airbytehq/airbyte-internal-issues/issues/8932
- In order to support non-local installations (i.e. EC2 instances)
- always create a `localhost` ingress-rule
- if `--host` was defined, create an additional `--host` ingress-rule
=> fix: add second ingress rule

internal/cmd/local/docker/docker.go
- fix https://github.com/airbytehq/airbyte-internal-issues/issues/8933
- change the priority order of options used when creating the docker client
- previously `WithHost` ran last which ensured that the `host` we defined was the one used
- now `WithHost` runs first, so that the `FromEnv` call can override the host correctly if `DOCKER_HOST` is defined
- this addresses an issue where the wrong host is being used and the user has no way to override this host
- the docker cli has no concept of `docker context`, otherwise the host could been fetched from the active `docker context`
=> fix: support DOCKER_HOST

internal/cmd/local/k8s/log.go, internal/cmd/local/k8s/log_test.go, internal/cmd/local/local/cmd.go, internal/cmd/version/version_test.go
- add a `k8s.Logger`
- prior to this change k8s warnings were sent directly to stdout
- after this change, k8s warnings will now be treated as debug output
- only be visible by passing the `-v` flag
=> fix: k8s warnings being handled improperly 

internal/cmd/local/k8s/cluster.go, internal/cmd/local/k8s/kind/config.go, internal/cmd/local/local/cmd.go, internal/cmd/local/local_install.go
This PR adds support for adding arbitrary extra volume mounts to the Kind cluster node. This makes it possible for developers who need/want to mount host volumes for iterating on services they develop (e.g. connector-builder)
Usage:
`abctl local install --volume /Users/angel/Developer/github/airbytehq/airbyte/airbyte-integrations/connectors:/mnt/connectors --values values.yaml`
`--volume` allows you to specify any arbitrary volume mount  and in conjunction with your own values.yaml you can specify the mounts you need:
example:
```
connector-builder-server:
env_vars:
PATH_TO_CONNECTORS: "/connectors"
extraVolumes:
- name: "connectors"
hostPath:
path: "/mnt/connectors"
type: DirectoryOrCreate
extraVolumeMounts:
- name: "connectors"
mountPath: /connectors
server: 
env_vars: …
```
=> feat: support for custom volume mounts

internal/cmd/cmd.go
- the `--dnt` flag was mostly removed in an earlier pr, this section of code was missed
=> chore: remove last reference to flagDNT

README.md, internal/cmd/local/local/cmd.go, internal/cmd/local/local_install.go
This PR adds support for a new `--low-resource-mode` mode that you can enable when running local install of Airbyte. 
This is useful when running in environments that have less resources.
=> feat: add a `--low-resource-mode` flag

abctl_install.sh
For some reasons `brew` doesn't pick up the the latest version of `abctl` on our tap. Running update seems to fix it.
Not sure if this is the right fix.
=> fix: run `brew update` before attempting to upgrade

internal/cmd/local/local_credentials.go
Instead of displaying
```
SUCCESS  Retreiving your credentials from 'airbyte-auth-secrets'
INFO    Credentials:
Email:
Password: *******
Client-Id: *******
Client-Secret: *******
```
display
```
SUCCESS  Retreiving your credentials from 'airbyte-auth-secrets'
INFO    Credentials:
Email: [not set]
Password: *******
Client-Id: *******
Client-Secret: *******
```
=> fix: if email is not defined, make it more clear

internal/cmd/local/local/cmd.go, internal/cmd/local/local/cmd_test.go
- fix https://github.com/airbytehq/airbyte-internal-issues/issues/9353
- instead of upgrading the existing ingress-nginx in place, uninstall it, then install it
- the upgrade sometimes get stuck with the error `0/1 nodes are available: 1 node(s) didn't have free ports for the requested pod ports` 
- manually killing the pod will resolve this problem
- so will uninstalling it first
- repurpose `checkHelmReleaseShouldInstall` method
- previously this method would only return `true` if the ingress-nginx controller should be installed/reinstalled
- now will return a state of what should happen
- `none` - do nothing
- `uninstall` - uninstall the existing ingress-nginx before installing a new version
- `install` - install the ingress-nginx controller
=> fix: ingress pods getting stuck when upgrading

go.mod, go.sum, internal/cmd/cmd.go, internal/cmd/local/local.go, internal/cmd/local/local_credentials.go, internal/cmd/local/local_install.go, internal/cmd/local/local_status.go, internal/cmd/local/local_uninstall.go, internal/cmd/version/version.go, internal/cmd/version/version_test.go, main.go
- replace [cobra](github.com/spf13/cobra) with [kong](https://github.com/alecthomas/kong)
- kong's approach is cleaner and easier to test
- cobra
```go
func NewCmdCredentials(provider k8s.Provider) *cobra.Command {
spinner := &pterm.DefaultSpinner
var (
flagSetPassword string
flagSetEmail    string
)
cmd := &cobra.Command{
Use:   "credentials",
Short: "Get Airbyte user credentials",
RunE: func(cmd *cobra.Command, args []string) error {
return telClient.Wrap(cmd.Context(), telemetry.Credentials, func() error {
// ...
})
},
}
cmd.Flags().StringVar(&flagSetEmail, "email", "", "specify the new email address for authentication")
cmd.Flags().StringVar(&flagSetPassword, "password", "", "specify the new password for authentication")
return cmd
}
```
- kong
```go
type Cmd struct {
Credentials …
```
=> feat: replace cobra with kong

.github/workflows/go.yml, .github/workflows/release.yml
https://github.com/airbytehq/airbyte-internal-issues/issues/9451
This adds a github workflow for releases. The workflow is triggered when a tag is pushed with the `v...` prefix (e.g. `v1.2.3`). The workflow sets `ABCTL_VERSION` to the tag name, sets up Go, builds all the releases using the existing script, creates a release, and uploads the artifacts.
I've changed the Go version used to `stable`, which should always pull the latest stable version. If you'd prefer to stick with `1.22.2` and manually update both files on new Go releases, I can change it.
This currently takes about 5 minutes. It builds the versions serially instead of in parallel, because that was easiest. It's probably fast enough, but if we want it to be faster we can possibly parallelize the builds for different …
=> ci: add github workflow for releases

.github/workflows/release.yml
https://github.com/airbytehq/airbyte-internal-issues/issues/9450
This adds steps to the release workflow to checkout the homebrew tap, update the version, and push a commit to that repo.
This depends on having write access to the homebrew tap repo, which is granted via [Deploy Keys](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/managing-deploy-keys#deploy-keys)
I made up a robot user for the git name/email here. I'm not sure if we have an actual user/account that would be better.
=> ci: update homebrew tap on release

internal/cmd/local/local/specs.go
Add the host.docker.internal to the ingress so that dockerized apps can easily communicate with Airbyte.
=> feat: add the host.docker.internal to the ingress so that dockerized apps can easily communicate with Airbyte.

.gitignore, internal/cmd/local/check.go, internal/cmd/local/check_test.go, internal/cmd/local/docker/docker.go, internal/cmd/local/docker/dockertest/dockertest.go, internal/cmd/local/local_install.go, internal/cmd/local/local_status.go, internal/cmd/local/local_uninstall.go
Capture the number of CPUs and the amount of memory available to the docker server.
=> feat: capture docker cpu/mem info

internal/cmd/cmd.go, internal/cmd/local/k8s/client.go, internal/cmd/local/k8s/k8stest/k8stest.go, internal/cmd/local/local.go, internal/cmd/local/local/cmd_test.go, internal/cmd/local/local_credentials.go, internal/cmd/local/local_deployments.go, internal/cmd/local/local_deployments_test.go, internal/cmd/local/localerr/localerr.go, internal/telemetry/client.go, main.go
- fix https://github.com/airbytehq/airbyte-internal-issues/issues/9582
- add a `abctl local deployments` sub command
- by default will list all the deployments
- if passed `--restart=[deployment name]`, will restart the provided deployment
- add `k8stest` package
- moved `mockK8Client` (from the existing tests) to `MockClient` in this package
- follows a similar model that the package `dockertest` uses
- update the default `k8s.Client` to be injectable (in `kong`)
- this enabled me to write tests for the `deployment` sub-command
- also adds the ability to write tests easier for other sub-commands (not in this PR)
=> feat: add the ability list and restart deployments

internal/cmd/cmd.go, internal/cmd/local/localerr/localerr.go, internal/cmd/local/localerr/localerr_test.go
- introduce a `LocalError` type
- combines an error message with a help message
- migrate all the existing errors with help messages to this type
=> chore: clean-up custom error and help message

internal/cmd/local/local/cmd.go, internal/cmd/local/local/cmd_test.go, internal/cmd/local/local/locate.go
Helm has an issue where it can confuse a local directory with a requested chart: https://github.com/helm/helm/issues/7862
For example, if you have a local, empty directory path `./airbyte/airbyte` and you request the `airbyte/airbyte` chart, abctl + helm will fail with `unable to install airbyte chart: unable to fetch chart airbyte/airbyte: Chart.yaml file is missing`
This change avoids that problem (currently only for the `airbyte/airbyte` chart when requesting the latest version) by determining the full URL of the chart and using that, which causes Helm to avoid looking at local directories.
I avoided handling the nginx chart and non-latest versions here for simplicity, but I could probably add support for those fairly easily.
=> fix: avoid helm conflict with local directory

.github/workflows/release.yml
Prevent me from creating invalid release tags like `0.14.0`. Release tags need to be like `v0.14.0`
=> ci: validate release tag name

internal/cmd/local/helm/helm.go, internal/cmd/local/paths/paths.go, internal/cmd/local/paths/paths_test.go
- potential fix for error `unable to install airbyte chart: unable to add airbyte chart repo: open /tmp/.helmrepo: permission denied`
- if `abctl` cannot write to `/tmp`, hopefully it can write to `~/.airbyte/abctl`, if it can't write to `~/.airbyte/abctl` then it can't run at all
- change the default location for the helm cache
- previously defaulted to `/tmp/.helmcache` and `/tmp/.helmrepo`
- now will use `~/.airbyte/abctl/.helmcache` and `~/.airbyte/abctl/.helmrepo`
=> fix: change helm cache directories

go.mod, go.sum, internal/cmd/local/k8s/cluster.go
- reverts airbytehq/abctl#102
- this update is causing issues with postgres user permissions
- will need to spend some cycles debugging why this doesn't work with the latest version of kind before updating again
- to repro (prior to reverting this PR being merged); 
`abctl local uninstall --persisted && abctl local install`
=> revert: "chore: update kind"

internal/cmd/local/local/install.go
If you pull images too many times, Docker Hub will rate limit you, and K8s will back off trying to pull images. This can grind abctl installs to a halt – in my experience it can take hours to recover from this.
This change makes these events clear warnings in the logs, so that the user knows what's going on immediately (while k8s spins behind the scenes).
There's a lot more that needs to be done in this area (image caching, better status reporting, etc) but this is a small, quick way to make the situation clearer to the user.
=> feat: warning logs when image pulls back off

internal/cmd/local/helm/helm.go
Tiny tweak to remove unnecessary `...-DEBUG...` noise from helm debug logs
=> fix: clean up helm debug logs

go.mod, go.sum, internal/cmd/local/local/install.go, internal/cmd/local/local/specs.go, internal/cmd/local/local/specs_test.go, internal/cmd/local/local_install.go
- add support for specifying multiple `--host` flags
- if no `--host` is provided, defaults to `""`, which allows for _all_ incoming connections to connect
- this will allow users to connect via ip-address, but only if they do _not_ specify any host 
- if a single `--host` is provided that host will be added to the ingress rule
- this will also add the host `localhost` and `host.docker.internal` automatically
- upgrade to go `1.23.1`
=> feat: add support for multiple hosts, default to no host

internal/cmd/local/k8s/client.go, internal/cmd/local/k8s/k8stest/k8stest.go, internal/cmd/local/local/cmd.go, internal/cmd/local/local/install.go
Stream bootloader logs to the debug output, unless they're at the "ERROR" level, then write them as error logs.
=> feat: stream bootloader logs

internal/cmd/local/local/install.go
In the previous pull request https://github.com/airbytehq/abctl/pull/103, it seems the YAML package was changed from `"k8s.io/apimachinery/pkg/util/yaml"` to `"gopkg.in/yaml.v2"`. This change is causing issues when people try to use `abctl` with `secrets.yaml`. During the parsing operation, the `metadata.name` property of the secret is not parsed properly.
Proposal is to return to previous package but maybe we can work to get to fix the unmarshall step using the new package.
=> fix: use k8s yaml lib

internal/cmd/local/k8s/client.go, internal/cmd/local/k8s/k8stest/k8stest.go, internal/cmd/local/local/install.go, internal/cmd/local/local/java_logs.go, internal/cmd/local/local/log_utils.go, internal/cmd/local/local/log_utils_test.go
This should give us a better error in the telemetry when, for example, the bootloader fails.
Before:
```
unable to install airbyte chart: unable to install helm: failed pre-install: 1 error occurred:
* pod airbyte-abctl-airbyte-bootloader failed
```
After:
```
unable to install airbyte chart:
pod airbyte-abctl-airbyte-bootloader: Caused by: io.airbyte.db.check.DatabaseCheckException: Unable to connect to the database.
```
=> feat: better reporting of airbyte chart errors

internal/cmd/local/local/install.go
We only want to unset any requests when running in low resource mode, that way we don't have runaway resource usage
=> fix(low-resource-mode): don't unset limits

internal/cmd/local/local/install.go
Fall back to helm error when no pods failed.
=> fix: fall back to helm error when no pods failed

README.md
- update the README to match the new default behavior of the `--host` flag (which changed in #110)
=> docs: update README to match new --host behavior

internal/cmd/local/local/install.go
- dynamic attribute names cause issues with our telemetry tracking
- removing this attribute for now, will need to revisit how to capture this data
=> fix: remove dynamic telemetry attr

internal/cmd/local/local/locate.go, internal/cmd/local/local/locate_test.go
- prior to this change the most recently published chart was always considered the _latest_ chart
- now the _latest_ chart will be the most recent chart that **does not** contain any sort of modifier after the release version
- e.g. given the latest releases of `1.0.0-beta-hash`, `1.0.0-alpha`, `0.463.124`, the _latest_ version would be `0.463.124`
=> fix: change what latest chart actually means

internal/cmd/local/local/install.go, internal/cmd/local/local/install_test.go, internal/cmd/local/local/testdata/values.yml, internal/cmd/local/local_install.go, internal/cmd/local/local_test.go
Validate the user's values file early, before telemetry for the install event starts.
=> fix: validate values file yaml early

internal/cmd/local/check.go
Capture some telemetry on docker cgroups support so we can potentially give a better error message for missing cgroup support
=> feat: capture docker cgroups info

internal/cmd/cmd.go, internal/update/update.go, internal/update/update_test.go, main.go
Just chipping away at some minor code cleanup.
=> refactor: break main into functions

internal/cmd/local/check.go, internal/cmd/local/check_test.go, internal/cmd/local/local_install.go, internal/cmd/local/local_test.go, internal/cmd/local/localerr/localerr.go
Since this validation happens before the `telemetry.Wrap` call, this should eliminate this category of errors from our error tracking.
=> feat: validate --host flag for IP address

internal/cmd/local/k8s/provider.go, internal/cmd/local/k8s/provider_test.go, internal/cmd/local/local/install.go, internal/cmd/local/local/install_test.go, internal/cmd/local/local/nginx.go
Set up some nginx config for request body size and timeouts.
Related issues:
- https://github.com/airbytehq/airbyte/issues/45423
- https://github.com/airbytehq/airbyte/issues/45156
- https://github.com/airbytehq/airbyte/issues/43893
- https://github.com/airbytehq/airbyte-internal-issues/issues/9859
Unfortunately, I think this will only work on new installs or uninstall + reinstall. In my tests, I couldn't get this to update my existing ingress.
The request body size is fairly easy to test by creating a postgres source with lots of tables/columns:
after:
I'm not sure how to test the timeout setting yet.
=> feat: nginx config for request size and timeouts

internal/cmd/local/local/install.go, internal/cmd/local/local/install_test.go
Bump helm timeout from 30 to 60 minutes to allow more time for the system to start and hopefully make a dent in timeout errors
=> fix: bump helm timeout to 60 minutes

internal/cmd/local/local_install.go
https://github.com/airbytehq/abctl/pull/121#issuecomment-2376707121
The default on the `--chart-version` flag doesn't work with the `xor` on the `--chart` and `--chart-version` flags.
The default "latest" was getting converted to "" anyway, so this change just sets the default to ""
=> fix: xor with --chart and --chart-version flags

go.mod, internal/cmd/cmd.go, internal/cmd/images/images_cmd.go, internal/cmd/images/manifest_cmd.go, internal/cmd/images/manifest_cmd_test.go, internal/cmd/images/testdata/enterprise.values.yaml, internal/cmd/local/check_test.go, internal/cmd/local/helm/airbyte_values.go, internal/cmd/local/helm/helm.go, internal/cmd/local/helm/locate.go, internal/cmd/local/helm/locate_test.go, internal/cmd/local/helm/nginx_values.go, internal/cmd/local/local.go, internal/cmd/local/local/cmd.go, internal/cmd/local/local/install.go, internal/cmd/local/local/install_test.go, internal/cmd/local/local/mock_test.go, internal/cmd/local/local/specs.go, internal/cmd/local/local/status.go, internal/cmd/local/local/testdata/expected-default.values.yaml, internal/cmd/local/local/testdata/invalid.values.yaml, internal/cmd/local/local/testdata/test-edition.values.yaml, internal/cmd/local/local_install.go, internal/cmd/local/local_test.go, internal/common/const.go, internal/telemetry/client.go, internal/telemetry/mock.go, internal/telemetry/noop.go, internal/telemetry/noop_test.go, internal/telemetry/segment.go
https://github.com/airbytehq/airbyte-internal-issues/issues/10018
This adds `abctl images manifest` which prints a list of container images used by the Airbyte platform.
```
abctl git:(abuch/images-cmd) ./abctl images manifest
airbyte/bootloader:1.1.0
airbyte/connector-builder-server:1.1.0
airbyte/cron:1.1.0
airbyte/db:1.1.0
airbyte/mc
airbyte/server:1.1.0
airbyte/webapp:1.1.0
airbyte/worker:1.1.0
airbyte/workload-api-server:1.1.0
airbyte/workload-launcher:1.1.0
bitnami/kubectl:1.28.9
busybox
minio/minio:RELEASE.2023-11-20T22-40-07Z
temporalio/auto-setup:1.23.0
```
It takes `--chart`, `--chart-version`, and `--values` flags (similar to `local install`) which can affect the outcome. For example, if you're `values.yaml` configures the enterprise edition, the image manifest will include …
=> feat: add images manifest command

internal/trace/trace.go
- sentry ui doesn't like it when no env is set
- or at least it is inconsistent with its behavior
=> fix: set sentry env

internal/telemetry/segment.go
When a user cancels an install by pressing Ctrl+C, the Go Context created in main.go is canceled. That context was being passed to the Segment telemetry client, which was trying to send an HTTP request using the canceled context, which would always fail. That resulted in a surprisingly large number of 'running' events. 
This change removes the context from the telemetry client's http calls so that this doesn't happen.
=> fix: ignore context in http request to segment

internal/cmd/cmd.go, internal/cmd/local/local/install_test.go, internal/trace/trace.go, main.go
Add user ID to sentry telemetry
Fixes https://github.com/airbytehq/airbyte-internal-issues/issues/10383
=> feat: add user ID to sentry telemetry

internal/cmd/local/local.go, internal/cmd/local/local_credentials.go, internal/cmd/local/local_deployments.go
- fix the error `couldn't find binding of type k8s.Client for parameter 2 of func(context.Context, telemetry.Client, k8s.Client) error(), use kong.Bind(k8s.Client)`
- moved the `defaultK8s` method from `local_credentials` to `local` and called the method from the deployments command
=> fix: deployments command failing

internal/cmd/images/manifest_cmd.go, internal/cmd/images/manifest_cmd_test.go, internal/cmd/local/docker/docker.go, internal/cmd/local/docker/dockertest/dockertest.go, internal/cmd/local/helm/helm.go, internal/cmd/local/k8s/cluster.go, internal/cmd/local/k8s/load_images.go, internal/cmd/local/local/install.go, internal/cmd/local/local_install.go, internal/common/set.go
Pull docker images (in parallel) and sideload them into the Kind cluster, before installing the helm chart.
In my testing, when starting from a clean machine (after running docker system prune --all), the first install takes ~10 minutes, and the next install takes ~2 minutes
=> feat: pre-pull images and sideload them into the cluster

internal/cmd/local/local.go, internal/cmd/local/local/cmd.go, internal/cmd/local/local_credentials.go, internal/cmd/local/local_deployments.go
There were two `defaultK8s` functions. Dedupe them.
=> refactor: dedupe defaultK8s func

internal/cmd/local/k8s/provider.go, internal/cmd/local/local_install.go
I'm trying to fix errors like the following, which I see quite often:
```
unable to initialize local command: error communicating with kubernetes: could not create rest config: stat /home/some-user-name/.airbyte/abctl/abctl.kubeconfig: no such file or directory
```
I can reproduce this locally if I
1. `abctl local install`
2. `rm ~/.airbyte/abctl/abctl.kubeconfig`
3. `abctl local install`
Maybe people are removing the `.airbyte/abctl` directory, thinking that will reset some things, or maybe they're moving the kubeconfig file somewhere for easy reference. Anyway, it's easy to make sure it always exists.
=> fix: ensure kubeconfig exists

internal/cmd/local/local/install.go, internal/cmd/local/local/install_test.go, internal/cmd/local/local/mock_test.go, internal/telemetry/segment.go, internal/telemetry/segment_test.go
Short logs from a pod are causing panics.
This also updates the Segment telemetry `Wrap` function to capture panics and write them to telemetry.
=> fix: fix log panic

internal/cmd/local/docker/docker.go, internal/cmd/local/docker/docker_test.go
`abctl` isn't handling Docker Desktop on Linux very well. Docker has multiple contexts, and `abctl` is making some guesses about which context to use, but it's often wrong on Docker Desktop on Linux. This is a problem because `kind` will end up using a different context and the user will run into strange errors.
This change execs `docker context inspect`, which describes the current context in detail. If this command fails, it will fail silently, and `abctl` will fall back to its original behavior (guessing at some common host socket locations).
=> fix: inspect docker context to find best host

internal/cmd/local/local/install.go, internal/cmd/local/local/install_test.go, internal/cmd/local/local/log_utils.go, internal/cmd/local/local/log_utils_test.go, internal/cmd/local/localerr/localerr.go
The log attachments in Sentry only contain the logs from the failed pod, not all pods. Very often it's the bootloader that's failed, but the bootloader logs don't say anything interesting – they just say the bootloader can't connect to the DB. So this PR would attach all logs from platform pods (only on airbyte chart failure) which hopefully gives us something more interesting to look at.
The code I wrote to try to parse java logs from the platform in `diagnoseAirbyteChartFailure` is mostly a failure. Most of the time it just returns 
```
unable to install airbyte chart: pod airbyte-abctl-airbyte-bootloader: unknown
```
There are a few variants in the telemetry, such as:
```
unable to install airbyte chart: pod airbyte-abctl-airbyte-bootloader: Caused by: …
```
=> fix: attach all logs on chart failure

internal/cmd/cmd.go, internal/cmd/local/local/install.go, main.go
- pull logs from anything that starts with `airbyte*`
- previously we only pulled logs from `airbyte-abctl-*` pods which didn't pull the `airbyte-db-0` and `airbyte-minio-0` logs
- this makes debugging certain failure scenarios more difficult than it needs to be
=> chore: pull logs from anything airbyte-*

internal/cmd/local/k8s/client.go, internal/cmd/local/k8s/k8stest/k8stest.go, internal/cmd/local/local/install.go, internal/cmd/local/local/install_test.go, internal/cmd/local/localerr/localerr.go
- fix https://github.com/airbytehq/airbyte-internal-issues/issues/8885
- If the previous `abctl local install` attempt was cut short it could get stuck in the helm state `pending-update`. This prevents the next `abctl local install` command from succeeding.  The error would be something similar to `another operation (install/upgrade/rollback) is in progress`
- The `abctl local install` command will now check for this error, attempt to resolve it (by removing the helm secrets) and trying the install/upgrade again.
- Additional information about why removing the helm secret bypassing this problem can be found [here](https://github.com/helm/helm/issues/8987#issuecomment-1082992461)
=> fix: unstick helm commands by removing helm secrets

internal/cmd/local/helm/airbyte_values.go, internal/cmd/local/local/install.go, internal/cmd/local/local/log_utils.go, internal/cmd/local/local/log_utils_test.go, internal/cmd/local/local/testdata/expected-default.values.yaml
This configures the bootloader to emit JSON formatted logs, and changes the log scanner in abctl to read JSON. This improves abctl's ability to recognize error logs from the bootloader and show them to the user.
The existing log scanner wasn't working anymore, and barely worked to begin with, so I removed it rather than keep it around to try to parse non-json logs.
=> feat: json logs from the bootloader

internal/cmd/local/helm/airbyte_values.go, internal/cmd/local/local_install.go
My team uses abctl to run airbyte locally on our development machines as part of our development flow.
for simplicity we disable auth during development. today we do this by passing a values file to abctl however it would be much nicer to have this option as a command line argument just like `--low-resource-mode`.
looked it up in the source code and saw its pretty easy to implement so i went ahead and implemented it.
=> feat: add optional flag to install airbyte with auth disabled

internal/cmd/local/docker/docker.go, internal/cmd/local/docker/docker_test.go
Dockers Net/HTTP client has Otel instrumentation enabled. URL's and other span fields may contain PII, or sensitive information.
=> refactor: do not sample Docker traces

docs/minio-to-local-storage-migration.md, internal/cmd/local/helm/airbyte_values.go, internal/cmd/local/local/cmd.go, internal/cmd/local/local/install.go, internal/cmd/local/local/testdata/expected-default.values.yaml, internal/cmd/local/local_install.go, internal/cmd/local/local_test.go
An example of performing an install on a previous Minio installation:
```
❯ go run main.go local install                           
INFO    Using Kubernetes provider:
Provider: kind
Kubeconfig: /Users/justin.pye/.airbyte/abctl/abctl.kubeconfig
Context: kind-airbyte-abctl
SUCCESS  Found Docker installation: version 28.2.1                                                                                           
WARNING  Found MinIO physical volume. Consider migrating it to local storage (see project docs)                                              
SUCCESS  Existing cluster 'airbyte-abctl' found                                                                                              
SUCCESS  Cluster 'airbyte-abctl' validation complete …
```
=> feat: default to local storage

internal/helm/airbyte_values.go, internal/helm/airbyte_values_test.go
The v1 Helm chart expects the secure cookie value as a string, not a boolean. A previous change in Abctl converted "true"/"false" to booleans, which broke this setting. This commit ensures the override value is treated as a string and adds tests to verify the behavior.
When using default values (no `--insecure-cookies` flag):
When setting the  `--insecure-cookies` flag:
=> fix: secure cookie setting

internal/k8s/ingress.go, internal/k8s/ingress_test.go, internal/service/install.go
Support backwards compatibility for webapp routing between v1 and v2+ charts. In v1 charts, the webapp is served from a dedicated webapp service, while in v2+ charts the webapp is served directly from the server service.
- Add chart version parameter to Ingress function
- Add version-specific routing logic
- Add test coverage for version boundaries and routing behavior
=> feat: route ingress traffic based on chart version

internal/helm/airbyte_values.go, internal/helm/airbyte_values_test.go
path to the `cookieSecureSetting` setting changed with v2 charts, so update abctl accordingly
=> fix: --insecure-cookies broke for v2 charts

internal/abctl/config.go, internal/cmd/cmd.go, internal/cmd/config/config.go, internal/cmd/config/init.go, internal/cmd/init/init.go, internal/k8s/client.go, internal/k8s/client_test.go, internal/k8s/config.go, internal/k8s/config_test.go, internal/k8s/k8stest/k8stest.go, internal/k8s/namespace.go, internal/service/manager.go, internal/service/manager_test.go
Works towards Airbyte dataplane installation and management. Adds `abctl config init` command to bootstrap abctl configuration from existing Airbyte Kubernetes deployments. Auto-detects Airbyte ConfigMaps ending with `-airbyte-env` suffix and extracts API endpoints and auth settings. It is envisioned that Abctl installation will automatically create the Abctl configmap during installation. Though I have added ample test coverage, and put some thought into this PR, there will might be some gaps. I'm hoping I can address these issues in future PRs before cutting a new release.
`abctl config init` Command
- Auto-detects source ConfigMap using -airbyte-env suffix pattern
- Extracts AIRBYTE_API_HOST, AIRBYTE_URL, and auth endpoints
- Creates abctl ConfigMap with the extracted config
- …
=> feat: `abctl config init` command
